# --- Base de donnees MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/event_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Execute automatiquement schema.sql au demarrage
spring.sql.init.mode=always

# --- Vues JSP ---
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

server.port=8080